# actions/labeler@v5 configuration

api:
  - changed-files:
      - any-glob-to-any-file:
          - "api/**/*"

service:
  - changed-files:
      - any-glob-to-any-file:
          - "service/**/*"

repository:
  - changed-files:
      - any-glob-to-any-file:
          - "repository/**/*"

models:
  - changed-files:
      - any-glob-to-any-file:
          - "models/**/*"

router:
  - changed-files:
      - any-glob-to-any-file:
          - "router/**/*"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "config/**/*"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "**/*.md"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "test/**/*"
          - "tests/**/*"
          - "**/*_test.go"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "docker/**/*"
          - "Dockerfile*"
          - "docker-compose*.yml"

ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "go.mod"
          - "go.sum"
