# golangci-lint 配置文件
# 详细文档: https://golangci-lint.run/usage/configuration/

run:
  timeout: 10m
  tests: true
  go: '1.24'

linters:
  disable-all: true
  enable:
    - errcheck       # 检查未处理的错误
    - gosimple       # 简化代码建议
    - govet          # 检查常见错误
    - ineffassign    # 检查无效赋值
    - staticcheck    # 静态分析检查
    - unused         # 检查未使用的常量、变量、函数等
    - gofmt          # 代码格式检查
    - goimports      # import 排序和分组

linters-settings:
  errcheck:
    # 排除常见的函数（这些返回值通常可以安全忽略）
    exclude-functions:
      - (io.Closer).Close
      - (*github.com/gorilla/websocket.Conn).Close
      - (*github.com/gorilla/websocket.Conn).SetReadDeadline
      - (*github.com/gorilla/websocket.Conn).SetWriteDeadline
      - (*github.com/gorilla/websocket.Conn).WriteMessage
      - (net.Conn).Close
      - (*go.mongodb.org/mongo-driver/mongo.Cursor).Close
      - (*go.mongodb.org/mongo-driver/mongo.Client).Disconnect
      - (*go.mongodb.org/mongo-driver/mongo.Database).Close
      - (net/http.Response.Body).Close
      - (*compress/gzip.Writer).Close
      - (*compress/gzip.Reader).Close
      - (*os.File).Close
      # 排除 redis 相关
      - (*github.com/redis/go-redis/v9.Client).Delete
      - (*github.com/redis/go-redis/v9.Client).Unlock
      # 排除 crypto/rand.Read
      - crypto/rand.Read
    # 禁用空白赋值检查，如 "x = _"
    check-blank: false
    # 禁用类型断言检查
    check-type-assertions: false

  govet:
    enable-all: true
    disable:
      - shadow  # shadow 变量检查过于严格

  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  # 排除特定错误模式的 errcheck 错误
  exclude:
    - "Error return value of .*\\.Close.* is not checked"
    - "Error return value of .*\\.Disconnect.* is not checked"
    - "Error return value of .*\\.Delete.* is not checked"
    - "Error return value of .*\\.Unlock.* is not checked"
    - "Error return value of .*\\.SetReadDeadline.* is not checked"
    - "Error return value of .*\\.SetWriteDeadline.* is not checked"
    - "Error return value of .*\\.WriteMessage.* is not checked"
    - "Error return value of .*\\.Read.* is not checked"
