# golangci-lint 配置文件
# 详细文档: https://golangci-lint.run/usage/configuration/

run:
  timeout: 10m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck       # 检查未处理的错误
    - gosimple       # 简化代码建议
    - govet          # 检查常见错误
    - ineffassign    # 检查无效赋值
    - staticcheck    # 静态分析检查
    - unused         # 检查未使用的常量、变量、函数等

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
