# 青羽写作系统配置文件

# 数据库配置
database:
  uri: "mongodb://localhost:27017"
  name: "Qingyu_writer"
  connect_timeout: 10s
  max_pool_size: 100
  min_pool_size: 10
  max_conn_idle_time: 60s
  retry_writes: true
  retry_reads: true

# 服务器配置
server:
  port: "8080"
  mode: "debug"  # debug or release

# JWT配置
jwt:
  secret: "qingyu_secret_key"  # 生产环境请修改为强密钥
  expiration_hours: 24

# AI配置（测试）
ai:
  api_key: "AIzaSyA3ENYLxj7OJAzylVgFcQL5AhsVJ03GEzo"  # 开发环境测试密钥
  base_url: "https://generativelanguage.googleapis.com/v1beta"
  model: "gemini-1.5-flash"  # 或者使用 gemini-1.5-pro
  max_tokens: 2000
  temperature: 0.7  # 0.0-1.0，值越高创造性越强