version: '3.8'

services:
  # ============ Prometheus（指标收集） ============
  prometheus:
    image: prom/prometheus:latest
    container_name: qingyu_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    networks:
      - qingyu_network
    restart: unless-stopped

  # ============ Grafana（可视化） ============
  grafana:
    image: grafana/grafana:latest
    container_name: qingyu_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      - qingyu_network
    depends_on:
      - prometheus
    restart: unless-stopped

  # ============ Alertmanager（告警管理） ============
  alertmanager:
    image: prom/alertmanager:latest
    container_name: qingyu_alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - qingyu_network
    restart: unless-stopped

  # ============ Node Exporter（系统指标收集） ============
  node_exporter:
    image: prom/node-exporter:latest
    container_name: qingyu_node_exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - qingyu_network
    restart: unless-stopped

networks:
  qingyu_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

