# 仅数据库服务的 Docker Compose 配置
# 用于无法拉取 golang 镜像时的临时方案
services:
  # MongoDB数据库
  mongodb:
    image: mongo:7.0
    container_name: qingyu-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: Qingyu_writer
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - qingyu-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: qingyu-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - qingyu-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  qingyu-network:
    name: qingyu-network
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local






