# 青羽写作系统配置文件 - Docker环境专用

# 数据库配置
database:
  type: mongodb
  primary:
    type: mongodb
    mongodb:
      uri: "mongodb://admin:changeme@mongodb:27017"  # Docker服务名（含认证）
      database: "Qingyu_writer"
      connect_timeout: 10s
      server_timeout: 30s
      max_pool_size: 100
      min_pool_size: 10
  indexing:
    auto_create: true
    background: true
  validation:
    enabled: true
    strict_mode: false
  sync:
    enabled: false
    interval: 5m

# Redis配置
redis:
  addr: "redis:6379"  # Docker服务名
  password: ""
  db: 0

# 服务器配置
server:
  port: "8080"
  mode: "debug"  # debug or release

# JWT配置
jwt:
  secret: "qingyu_secret_key"  # 生产环境请修改为强密钥
  expiration_hours: 24

# AI配置（测试）
ai:
  api_key: ""  # 开发环境测试密钥
  base_url: "https://generativelanguage.googleapis.com/v1beta"
  model: "gemini-1.5-flash"  # 或者使用 gemini-1.5-pro
  max_tokens: 2000
  temperature: 0.7  # 0.0-1.0，值越高创造性越强



