global:
  resolve_timeout: 5m

# 告警路由配置
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'

  routes:
    # 严重告警立即通知
    - match:
        severity: critical
      receiver: 'critical'
      group_wait: 0s
      repeat_interval: 4h

    # 警告类告警
    - match:
        severity: warning
      receiver: 'warning'
      group_wait: 30s
      repeat_interval: 12h

    # 信息类告警
    - match:
        severity: info
      receiver: 'info'
      group_wait: 5m
      repeat_interval: 24h

# 接收器配置
receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://qingyu_backend:8080/api/v1/webhook/alert'
        send_resolved: true

  - name: 'critical'
    webhook_configs:
      - url: 'http://qingyu_backend:8080/api/v1/webhook/alert/critical'
        send_resolved: true
    # 可以添加邮件通知
    # email_configs:
    #   - to: 'admin@example.com'
    #     from: 'alertmanager@example.com'
    #     smarthost: 'smtp.gmail.com:587'
    #     auth_username: 'alertmanager@example.com'
    #     auth_password: 'your_password'

  - name: 'warning'
    webhook_configs:
      - url: 'http://qingyu_backend:8080/api/v1/webhook/alert/warning'
        send_resolved: true

  - name: 'info'
    webhook_configs:
      - url: 'http://qingyu_backend:8080/api/v1/webhook/alert/info'
        send_resolved: true

# 抑制规则
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

