#!/usr/bin/env python3
"""生成性能对比报告"""

import sys
import json
import argparse
import re
from pathlib import Path

def load_result(filename):
    """加载测试结果"""
    with open(filename, 'r') as f:
        return json.load(f)

def calculate_improvement(before, after):
    """计算改善百分比（对于延迟，越小越好；对于吞吐量，越大越好）"""
    if before == 0:
        return 0.0
    return ((before - after) / before) * 100

def calculate_throughput_improvement(before, after):
    """计算吞吐量提升百分比（越大越好）"""
    if before == 0:
        return 0.0
    return ((after - before) / before) * 100

def duration_to_ms(duration_str):
    """将duration字符串转换为毫秒数"""
    # 格式: "100ms" 或 "1s500ms" 或 "2s" 或纯数字
    duration_str = duration_str.strip()

    # 使用正则表达式提取秒和毫秒
    # 匹配模式: 数字+s, 数字+ms
    pattern = r'(\d+)s(\d+)ms|(\d+)ms|(\d+)s'
    match = re.search(pattern, duration_str)

    if match:
        if match.group(1) and match.group(2):  # 1s500ms 格式
            seconds = int(match.group(1))
            milliseconds = int(match.group(2))
            return seconds * 1000 + milliseconds
        elif match.group(3):  # 100ms 格式
            return int(match.group(3))
        elif match.group(4):  # 2s 格式
            return int(match.group(4)) * 1000

    # 如果都不匹配，尝试直接转换为数字（纯毫秒）
    try:
        return int(duration_str)
    except ValueError:
        return 0

def generate_markdown_report(with_cache, without_cache, output_file):
    """生成Markdown格式的对比报告"""

    # 计算改善指标
    avg_latency_without = duration_to_ms(without_cache.get('avg_latency', '0ms'))
    avg_latency_with = duration_to_ms(with_cache.get('avg_latency', '0ms'))
    latency_improvement = calculate_improvement(avg_latency_without, avg_latency_with)

    throughput_without = without_cache.get('throughput', 0)
    throughput_with = with_cache.get('throughput', 0)
    throughput_improvement = calculate_throughput_improvement(throughput_without, throughput_with)

    # 计算成功率
    success_rate_without = (without_cache.get('success_count', 0) / without_cache.get('total_requests', 1)) * 100
    success_rate_with = (with_cache.get('success_count', 0) / with_cache.get('total_requests', 1)) * 100

    report = f"""# 性能对比测试报告

## 测试配置

- 基础URL: {without_cache.get('base_url', 'N/A')}
- 测试请求数: {without_cache.get('total_requests', 'N/A')}
- 并发数: {without_cache.get('concurrent', 'N/A')}

## 性能对比

### 响应时间

| 指标 | 无缓存 | 有缓存 | 改善 |
|------|--------|--------|------|
| 平均延迟 | {avg_latency_without} ms | {avg_latency_with} ms | {latency_improvement:.2f}% |
| P95延迟 | {without_cache.get('p95_latency', 'N/A')} | {with_cache.get('p95_latency', 'N/A')} | - |
| P99延迟 | {without_cache.get('p99_latency', 'N/A')} | {with_cache.get('p99_latency', 'N/A')} | - |

### 吞吐量

| 指标 | 无缓存 | 有缓存 | 改善 |
|------|--------|--------|------|
| 请求/秒 | {throughput_without:.2f} | {throughput_with:.2f} | {throughput_improvement:.2f}% |

### 成功率

| 指标 | 无缓存 | 有缓存 |
|------|--------|--------|
| 成功率 | {success_rate_without:.2f}% | {success_rate_with:.2f}% |

## 结论

"""

    if latency_improvement >= 30:
        report += f"[PASS] 响应时间改善达标 ({latency_improvement:.2f}% >= 30%)\\n"
    else:
        report += f"[FAIL] 响应时间改善未达标 ({latency_improvement:.2f}% < 30%)\\n"

    report += "\\n---\\n\\nGenerated by Block 3 Stage 4 Verification Tool\\n"

    # 写入文件，使用UTF-8编码
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(report)

    print(f"报告已生成: {output_file}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='生成性能对比报告')
    parser.add_argument('--with-cache', required=True, help='有缓存的测试结果JSON文件')
    parser.add_argument('--without-cache', required=True, help='无缓存的测试结果JSON文件')
    parser.add_argument('--output', required=True, help='输出报告文件路径')

    args = parser.parse_args()

    with_cache = load_result(args.with_cache)
    without_cache = load_result(args.without_cache)

    generate_markdown_report(with_cache, without_cache, args.output)
