// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc2
// source: ai_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ChapterId     string                 `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Options       *GenerateOptions       `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateContentRequest) Reset() {
	*x = GenerateContentRequest{}
	mi := &file_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateContentRequest) ProtoMessage() {}

func (x *GenerateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateContentRequest.ProtoReflect.Descriptor instead.
func (*GenerateContentRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateContentRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GenerateContentRequest) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *GenerateContentRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateContentRequest) GetOptions() *GenerateOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type GenerateOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                           // 模型名称
	MaxTokens     int32                  `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"` // 最大 Token 数
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`             // 温度参数 0.0-1.0
	Stop          []string               `protobuf:"bytes,4,rep,name=stop,proto3" json:"stop,omitempty"`                             // 停止词
	Stream        bool                   `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`                        // 是否流式输出
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateOptions) Reset() {
	*x = GenerateOptions{}
	mi := &file_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOptions) ProtoMessage() {}

func (x *GenerateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOptions.ProtoReflect.Descriptor instead.
func (*GenerateOptions) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateOptions) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateOptions) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GenerateOptions) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateOptions) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *GenerateOptions) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type GenerateContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,2,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	GeneratedAt   int64                  `protobuf:"varint,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateContentResponse) Reset() {
	*x = GenerateContentResponse{}
	mi := &file_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateContentResponse) ProtoMessage() {}

func (x *GenerateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateContentResponse.ProtoReflect.Descriptor instead.
func (*GenerateContentResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateContentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GenerateContentResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *GenerateContentResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateContentResponse) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

type RAGQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Filters       *RAGFilters            `protobuf:"bytes,3,opt,name=filters,proto3" json:"filters,omitempty"`
	TopK          int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"` // 返回结果数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGQueryRequest) Reset() {
	*x = RAGQueryRequest{}
	mi := &file_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGQueryRequest) ProtoMessage() {}

func (x *RAGQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGQueryRequest.ProtoReflect.Descriptor instead.
func (*RAGQueryRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *RAGQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RAGQueryRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RAGQueryRequest) GetFilters() *RAGFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *RAGQueryRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type RAGFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocTypes      []string               `protobuf:"bytes,1,rep,name=doc_types,json=docTypes,proto3" json:"doc_types,omitempty"`             // 文档类型过滤
	CharacterIds  []string               `protobuf:"bytes,2,rep,name=character_ids,json=characterIds,proto3" json:"character_ids,omitempty"` // 角色 ID 过滤
	TimelineIds   []string               `protobuf:"bytes,3,rep,name=timeline_ids,json=timelineIds,proto3" json:"timeline_ids,omitempty"`    // 时间线 ID 过滤
	ChapterIds    []string               `protobuf:"bytes,4,rep,name=chapter_ids,json=chapterIds,proto3" json:"chapter_ids,omitempty"`       // 章节 ID 过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGFilters) Reset() {
	*x = RAGFilters{}
	mi := &file_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGFilters) ProtoMessage() {}

func (x *RAGFilters) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGFilters.ProtoReflect.Descriptor instead.
func (*RAGFilters) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *RAGFilters) GetDocTypes() []string {
	if x != nil {
		return x.DocTypes
	}
	return nil
}

func (x *RAGFilters) GetCharacterIds() []string {
	if x != nil {
		return x.CharacterIds
	}
	return nil
}

func (x *RAGFilters) GetTimelineIds() []string {
	if x != nil {
		return x.TimelineIds
	}
	return nil
}

func (x *RAGFilters) GetChapterIds() []string {
	if x != nil {
		return x.ChapterIds
	}
	return nil
}

type RAGQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RAGResult           `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGQueryResponse) Reset() {
	*x = RAGQueryResponse{}
	mi := &file_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGQueryResponse) ProtoMessage() {}

func (x *RAGQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGQueryResponse.ProtoReflect.Descriptor instead.
func (*RAGQueryResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *RAGQueryResponse) GetResults() []*RAGResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RAGQueryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RAGResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	DocType       string                 `protobuf:"bytes,4,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGResult) Reset() {
	*x = RAGResult{}
	mi := &file_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGResult) ProtoMessage() {}

func (x *RAGResult) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGResult.ProtoReflect.Descriptor instead.
func (*RAGResult) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{6}
}

func (x *RAGResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RAGResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RAGResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RAGResult) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

func (x *RAGResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ChapterId     string                 `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	TaskType      string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"` // continue_writing, create_chapter, review_content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest) Reset() {
	*x = ContextRequest{}
	mi := &file_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest) ProtoMessage() {}

func (x *ContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest.ProtoReflect.Descriptor instead.
func (*ContextRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{7}
}

func (x *ContextRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ContextRequest) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *ContextRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type ContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      string                 `protobuf:"bytes,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Context       *WorkspaceContext      `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	TokenCount    int32                  `protobuf:"varint,3,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextResponse) Reset() {
	*x = ContextResponse{}
	mi := &file_ai_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResponse) ProtoMessage() {}

func (x *ContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResponse.ProtoReflect.Descriptor instead.
func (*ContextResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{8}
}

func (x *ContextResponse) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *ContextResponse) GetContext() *WorkspaceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ContextResponse) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

type WorkspaceContext struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PreviousChapters []*ChapterSummary      `protobuf:"bytes,1,rep,name=previous_chapters,json=previousChapters,proto3" json:"previous_chapters,omitempty"`
	ActiveCharacters []*CharacterInfo       `protobuf:"bytes,2,rep,name=active_characters,json=activeCharacters,proto3" json:"active_characters,omitempty"`
	TimelineEvents   []*TimelineEvent       `protobuf:"bytes,3,rep,name=timeline_events,json=timelineEvents,proto3" json:"timeline_events,omitempty"`
	OutlineNodes     []*OutlineNode         `protobuf:"bytes,4,rep,name=outline_nodes,json=outlineNodes,proto3" json:"outline_nodes,omitempty"`
	WorldSettings    *WorldSettings         `protobuf:"bytes,5,opt,name=world_settings,json=worldSettings,proto3" json:"world_settings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkspaceContext) Reset() {
	*x = WorkspaceContext{}
	mi := &file_ai_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceContext) ProtoMessage() {}

func (x *WorkspaceContext) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceContext.ProtoReflect.Descriptor instead.
func (*WorkspaceContext) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{9}
}

func (x *WorkspaceContext) GetPreviousChapters() []*ChapterSummary {
	if x != nil {
		return x.PreviousChapters
	}
	return nil
}

func (x *WorkspaceContext) GetActiveCharacters() []*CharacterInfo {
	if x != nil {
		return x.ActiveCharacters
	}
	return nil
}

func (x *WorkspaceContext) GetTimelineEvents() []*TimelineEvent {
	if x != nil {
		return x.TimelineEvents
	}
	return nil
}

func (x *WorkspaceContext) GetOutlineNodes() []*OutlineNode {
	if x != nil {
		return x.OutlineNodes
	}
	return nil
}

func (x *WorkspaceContext) GetWorldSettings() *WorldSettings {
	if x != nil {
		return x.WorldSettings
	}
	return nil
}

type ChapterSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterSummary) Reset() {
	*x = ChapterSummary{}
	mi := &file_ai_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterSummary) ProtoMessage() {}

func (x *ChapterSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterSummary.ProtoReflect.Descriptor instead.
func (*ChapterSummary) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{10}
}

func (x *ChapterSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChapterSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChapterSummary) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ChapterSummary) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type CharacterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         []string               `protobuf:"bytes,3,rep,name=alias,proto3" json:"alias,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Traits        []string               `protobuf:"bytes,5,rep,name=traits,proto3" json:"traits,omitempty"`
	Background    string                 `protobuf:"bytes,6,opt,name=background,proto3" json:"background,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterInfo) Reset() {
	*x = CharacterInfo{}
	mi := &file_ai_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterInfo) ProtoMessage() {}

func (x *CharacterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterInfo.ProtoReflect.Descriptor instead.
func (*CharacterInfo) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{11}
}

func (x *CharacterInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CharacterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterInfo) GetAlias() []string {
	if x != nil {
		return x.Alias
	}
	return nil
}

func (x *CharacterInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CharacterInfo) GetTraits() []string {
	if x != nil {
		return x.Traits
	}
	return nil
}

func (x *CharacterInfo) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

type TimelineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Impact        string                 `protobuf:"bytes,4,opt,name=impact,proto3" json:"impact,omitempty"`
	Participants  []string               `protobuf:"bytes,5,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEvent) Reset() {
	*x = TimelineEvent{}
	mi := &file_ai_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEvent) ProtoMessage() {}

func (x *TimelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEvent.ProtoReflect.Descriptor instead.
func (*TimelineEvent) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{12}
}

func (x *TimelineEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimelineEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TimelineEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TimelineEvent) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *TimelineEvent) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

type OutlineNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutlineNode) Reset() {
	*x = OutlineNode{}
	mi := &file_ai_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutlineNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutlineNode) ProtoMessage() {}

func (x *OutlineNode) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutlineNode.ProtoReflect.Descriptor instead.
func (*OutlineNode) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{13}
}

func (x *OutlineNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutlineNode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OutlineNode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OutlineNode) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type WorldSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Settings      map[string]string      `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSettings) Reset() {
	*x = WorldSettings{}
	mi := &file_ai_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSettings) ProtoMessage() {}

func (x *WorldSettings) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSettings.ProtoReflect.Descriptor instead.
func (*WorldSettings) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{14}
}

func (x *WorldSettings) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorldSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorldSettings) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorldSettings) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type AgentExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowType  string                 `protobuf:"bytes,1,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"` // a2a_pipeline, outline_generation, etc.
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExecutionRequest) Reset() {
	*x = AgentExecutionRequest{}
	mi := &file_ai_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExecutionRequest) ProtoMessage() {}

func (x *AgentExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExecutionRequest.ProtoReflect.Descriptor instead.
func (*AgentExecutionRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{15}
}

func (x *AgentExecutionRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *AgentExecutionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AgentExecutionRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type AgentExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // running, completed, failed
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // JSON 格式的结果
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,5,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExecutionResponse) Reset() {
	*x = AgentExecutionResponse{}
	mi := &file_ai_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExecutionResponse) ProtoMessage() {}

func (x *AgentExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExecutionResponse.ProtoReflect.Descriptor instead.
func (*AgentExecutionResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{16}
}

func (x *AgentExecutionResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *AgentExecutionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentExecutionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AgentExecutionResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *AgentExecutionResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_ai_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{17}
}

func (x *EmbedRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *EmbedRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*Embedding           `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_ai_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{18}
}

func (x *EmbedResponse) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Dimension     int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_ai_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{19}
}

func (x *Embedding) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *Embedding) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_ai_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{20}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // healthy, degraded, unhealthy
	Checks        map[string]string      `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_ai_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{21}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetChecks() map[string]string {
	if x != nil {
		return x.Checks
	}
	return nil
}

var File_ai_service_proto protoreflect.FileDescriptor

const file_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x10ai_service.proto\x12\tqingyu.ai\"\xa4\x01\n" +
	"\x16GenerateContentRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\tR\tchapterId\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x124\n" +
	"\aoptions\x18\x04 \x01(\v2\x1a.qingyu.ai.GenerateOptionsR\aoptions\"\x94\x01\n" +
	"\x0fGenerateOptions\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x12\n" +
	"\x04stop\x18\x04 \x03(\tR\x04stop\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\"\x8d\x01\n" +
	"\x17GenerateContentResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vtokens_used\x18\x02 \x01(\x05R\n" +
	"tokensUsed\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12!\n" +
	"\fgenerated_at\x18\x04 \x01(\x03R\vgeneratedAt\"\x8c\x01\n" +
	"\x0fRAGQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12/\n" +
	"\afilters\x18\x03 \x01(\v2\x15.qingyu.ai.RAGFiltersR\afilters\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\"\x92\x01\n" +
	"\n" +
	"RAGFilters\x12\x1b\n" +
	"\tdoc_types\x18\x01 \x03(\tR\bdocTypes\x12#\n" +
	"\rcharacter_ids\x18\x02 \x03(\tR\fcharacterIds\x12!\n" +
	"\ftimeline_ids\x18\x03 \x03(\tR\vtimelineIds\x12\x1f\n" +
	"\vchapter_ids\x18\x04 \x03(\tR\n" +
	"chapterIds\"X\n" +
	"\x10RAGQueryResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.qingyu.ai.RAGResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe3\x01\n" +
	"\tRAGResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12\x19\n" +
	"\bdoc_type\x18\x04 \x01(\tR\adocType\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".qingyu.ai.RAGResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x0eContextRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\tR\tchapterId\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\"\x86\x01\n" +
	"\x0fContextResponse\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\tR\btaskType\x125\n" +
	"\acontext\x18\x02 \x01(\v2\x1b.qingyu.ai.WorkspaceContextR\acontext\x12\x1f\n" +
	"\vtoken_count\x18\x03 \x01(\x05R\n" +
	"tokenCount\"\xe2\x02\n" +
	"\x10WorkspaceContext\x12F\n" +
	"\x11previous_chapters\x18\x01 \x03(\v2\x19.qingyu.ai.ChapterSummaryR\x10previousChapters\x12E\n" +
	"\x11active_characters\x18\x02 \x03(\v2\x18.qingyu.ai.CharacterInfoR\x10activeCharacters\x12A\n" +
	"\x0ftimeline_events\x18\x03 \x03(\v2\x18.qingyu.ai.TimelineEventR\x0etimelineEvents\x12;\n" +
	"\routline_nodes\x18\x04 \x03(\v2\x16.qingyu.ai.OutlineNodeR\foutlineNodes\x12?\n" +
	"\x0eworld_settings\x18\x05 \x01(\v2\x18.qingyu.ai.WorldSettingsR\rworldSettings\"f\n" +
	"\x0eChapterSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\"\x9b\x01\n" +
	"\rCharacterInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x03(\tR\x05alias\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06traits\x18\x05 \x03(\tR\x06traits\x12\x1e\n" +
	"\n" +
	"background\x18\x06 \x01(\tR\n" +
	"background\"\x93\x01\n" +
	"\rTimelineEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06impact\x18\x04 \x01(\tR\x06impact\x12\"\n" +
	"\fparticipants\x18\x05 \x03(\tR\fparticipants\"k\n" +
	"\vOutlineNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\"\xd6\x01\n" +
	"\rWorldSettings\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12B\n" +
	"\bsettings\x18\x04 \x03(\v2&.qingyu.ai.WorldSettings.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x01\n" +
	"\x15AgentExecutionRequest\x12#\n" +
	"\rworkflow_type\x18\x01 \x01(\tR\fworkflowType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12P\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v20.qingyu.ai.AgentExecutionRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\x16AgentExecutionResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\x12\x1f\n" +
	"\vtokens_used\x18\x05 \x01(\x05R\n" +
	"tokensUsed\":\n" +
	"\fEmbedRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"E\n" +
	"\rEmbedResponse\x124\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x14.qingyu.ai.EmbeddingR\n" +
	"embeddings\"A\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension\"\x14\n" +
	"\x12HealthCheckRequest\"\xac\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12B\n" +
	"\x06checks\x18\x02 \x03(\v2*.qingyu.ai.HealthCheckResponse.ChecksEntryR\x06checks\x1a9\n" +
	"\vChecksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd8\x03\n" +
	"\tAIService\x12X\n" +
	"\x0fGenerateContent\x12!.qingyu.ai.GenerateContentRequest\x1a\".qingyu.ai.GenerateContentResponse\x12I\n" +
	"\x0eQueryKnowledge\x12\x1a.qingyu.ai.RAGQueryRequest\x1a\x1b.qingyu.ai.RAGQueryResponse\x12C\n" +
	"\n" +
	"GetContext\x12\x19.qingyu.ai.ContextRequest\x1a\x1a.qingyu.ai.ContextResponse\x12S\n" +
	"\fExecuteAgent\x12 .qingyu.ai.AgentExecutionRequest\x1a!.qingyu.ai.AgentExecutionResponse\x12>\n" +
	"\tEmbedText\x12\x17.qingyu.ai.EmbedRequest\x1a\x18.qingyu.ai.EmbedResponse\x12L\n" +
	"\vHealthCheck\x12\x1d.qingyu.ai.HealthCheckRequest\x1a\x1e.qingyu.ai.HealthCheckResponseB\x1cZ\x1aQingyu_backend/pkg/grpc/pbb\x06proto3"

var (
	file_ai_service_proto_rawDescOnce sync.Once
	file_ai_service_proto_rawDescData []byte
)

func file_ai_service_proto_rawDescGZIP() []byte {
	file_ai_service_proto_rawDescOnce.Do(func() {
		file_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)))
	})
	return file_ai_service_proto_rawDescData
}

var file_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_ai_service_proto_goTypes = []any{
	(*GenerateContentRequest)(nil),  // 0: qingyu.ai.GenerateContentRequest
	(*GenerateOptions)(nil),         // 1: qingyu.ai.GenerateOptions
	(*GenerateContentResponse)(nil), // 2: qingyu.ai.GenerateContentResponse
	(*RAGQueryRequest)(nil),         // 3: qingyu.ai.RAGQueryRequest
	(*RAGFilters)(nil),              // 4: qingyu.ai.RAGFilters
	(*RAGQueryResponse)(nil),        // 5: qingyu.ai.RAGQueryResponse
	(*RAGResult)(nil),               // 6: qingyu.ai.RAGResult
	(*ContextRequest)(nil),          // 7: qingyu.ai.ContextRequest
	(*ContextResponse)(nil),         // 8: qingyu.ai.ContextResponse
	(*WorkspaceContext)(nil),        // 9: qingyu.ai.WorkspaceContext
	(*ChapterSummary)(nil),          // 10: qingyu.ai.ChapterSummary
	(*CharacterInfo)(nil),           // 11: qingyu.ai.CharacterInfo
	(*TimelineEvent)(nil),           // 12: qingyu.ai.TimelineEvent
	(*OutlineNode)(nil),             // 13: qingyu.ai.OutlineNode
	(*WorldSettings)(nil),           // 14: qingyu.ai.WorldSettings
	(*AgentExecutionRequest)(nil),   // 15: qingyu.ai.AgentExecutionRequest
	(*AgentExecutionResponse)(nil),  // 16: qingyu.ai.AgentExecutionResponse
	(*EmbedRequest)(nil),            // 17: qingyu.ai.EmbedRequest
	(*EmbedResponse)(nil),           // 18: qingyu.ai.EmbedResponse
	(*Embedding)(nil),               // 19: qingyu.ai.Embedding
	(*HealthCheckRequest)(nil),      // 20: qingyu.ai.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 21: qingyu.ai.HealthCheckResponse
	nil,                             // 22: qingyu.ai.RAGResult.MetadataEntry
	nil,                             // 23: qingyu.ai.WorldSettings.SettingsEntry
	nil,                             // 24: qingyu.ai.AgentExecutionRequest.ParametersEntry
	nil,                             // 25: qingyu.ai.HealthCheckResponse.ChecksEntry
}
var file_ai_service_proto_depIdxs = []int32{
	1,  // 0: qingyu.ai.GenerateContentRequest.options:type_name -> qingyu.ai.GenerateOptions
	4,  // 1: qingyu.ai.RAGQueryRequest.filters:type_name -> qingyu.ai.RAGFilters
	6,  // 2: qingyu.ai.RAGQueryResponse.results:type_name -> qingyu.ai.RAGResult
	22, // 3: qingyu.ai.RAGResult.metadata:type_name -> qingyu.ai.RAGResult.MetadataEntry
	9,  // 4: qingyu.ai.ContextResponse.context:type_name -> qingyu.ai.WorkspaceContext
	10, // 5: qingyu.ai.WorkspaceContext.previous_chapters:type_name -> qingyu.ai.ChapterSummary
	11, // 6: qingyu.ai.WorkspaceContext.active_characters:type_name -> qingyu.ai.CharacterInfo
	12, // 7: qingyu.ai.WorkspaceContext.timeline_events:type_name -> qingyu.ai.TimelineEvent
	13, // 8: qingyu.ai.WorkspaceContext.outline_nodes:type_name -> qingyu.ai.OutlineNode
	14, // 9: qingyu.ai.WorkspaceContext.world_settings:type_name -> qingyu.ai.WorldSettings
	23, // 10: qingyu.ai.WorldSettings.settings:type_name -> qingyu.ai.WorldSettings.SettingsEntry
	24, // 11: qingyu.ai.AgentExecutionRequest.parameters:type_name -> qingyu.ai.AgentExecutionRequest.ParametersEntry
	19, // 12: qingyu.ai.EmbedResponse.embeddings:type_name -> qingyu.ai.Embedding
	25, // 13: qingyu.ai.HealthCheckResponse.checks:type_name -> qingyu.ai.HealthCheckResponse.ChecksEntry
	0,  // 14: qingyu.ai.AIService.GenerateContent:input_type -> qingyu.ai.GenerateContentRequest
	3,  // 15: qingyu.ai.AIService.QueryKnowledge:input_type -> qingyu.ai.RAGQueryRequest
	7,  // 16: qingyu.ai.AIService.GetContext:input_type -> qingyu.ai.ContextRequest
	15, // 17: qingyu.ai.AIService.ExecuteAgent:input_type -> qingyu.ai.AgentExecutionRequest
	17, // 18: qingyu.ai.AIService.EmbedText:input_type -> qingyu.ai.EmbedRequest
	20, // 19: qingyu.ai.AIService.HealthCheck:input_type -> qingyu.ai.HealthCheckRequest
	2,  // 20: qingyu.ai.AIService.GenerateContent:output_type -> qingyu.ai.GenerateContentResponse
	5,  // 21: qingyu.ai.AIService.QueryKnowledge:output_type -> qingyu.ai.RAGQueryResponse
	8,  // 22: qingyu.ai.AIService.GetContext:output_type -> qingyu.ai.ContextResponse
	16, // 23: qingyu.ai.AIService.ExecuteAgent:output_type -> qingyu.ai.AgentExecutionResponse
	18, // 24: qingyu.ai.AIService.EmbedText:output_type -> qingyu.ai.EmbedResponse
	21, // 25: qingyu.ai.AIService.HealthCheck:output_type -> qingyu.ai.HealthCheckResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_ai_service_proto_init() }
func file_ai_service_proto_init() {
	if File_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_service_proto_goTypes,
		DependencyIndexes: file_ai_service_proto_depIdxs,
		MessageInfos:      file_ai_service_proto_msgTypes,
	}.Build()
	File_ai_service_proto = out.File
	file_ai_service_proto_goTypes = nil
	file_ai_service_proto_depIdxs = nil
}
